on:
  push:
    branches:
      - main

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  SCOPE: ${{ secrets.SCOPE }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create config.js
        run: |
          echo "export const CLIENT_ID = '${{ secrets.CLIENT_ID }}';" > config.js
          echo "export const SCOPE = '${{ secrets.SCOPE }}';" >> config.js
          echo "export const REDIRECT_URI = '${{ secrets.REDIRECT_URI }}';" >> config.js
